apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${IMAGE_NAME}
  labels:
    app: ${IMAGE_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${IMAGE_NAME}
  template:
    metadata:
      labels:
        app: ${IMAGE_NAME}
    spec:
      containers:
        - name: ${IMAGE_NAME}
          image: ${IMAGE_WITH_SHA}
          ports:
            - containerPort: 50051
      imagePullSecrets:
        - name: github-auth
---
apiVersion: v1
kind: Service
metadata:
  name: ${IMAGE_NAME}
  labels:
    app: ${IMAGE_NAME}
spec:
  type: ClusterIP
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP
      name: http
  selector:
    app: ${IMAGE_NAME}
